### ISSUE TITLE
Timepicker popup closes automatically before a value is accepted

### ISSUE THREAD

**Issue by JimTim** [arfedulov/semantic-ui-calendar-react#1]
If I click in the timepicker on the values ​​00:00, 16:00 - 23:00, the popup of the timepicker closes. The onChange method is not called. But when I click on the other hours, the minute popup appears. onchange method works there too.

**Comment by JimTim** [comment]
This also happens in the live examples

**Comment by arfedulov** [comment]
Yes, i see. Will work on it.

**Comment by JimTim** [comment]
Perfect, Thx. Thanks also for the fantastic port.

**Comment by arfedulov** [comment]
I'm not sure but seems like it's somehow related with this https://github.com/Semantic-Org/Semantic-UI-React/issues/1580. Now I just set Portal's ``closeOnDocumentClick`` to ``false``. Probably it's not a good solution but solves the problem.
