### ISSUE TITLE
Unable to select single date in DatesRangeInput

### ISSUE THREAD

**Issue by syntext** [arfedulov/semantic-ui-calendar-react#103]
It is impossible to select a single date when using DateRangeInput. When I click for the second time on a specific date I'm expecting this to be handled as an end date. Instead it simply deselects the date. 

If this is desired behavior perhaps an option can be added to choose between the two types of behavior.

Version: 0.14.2
Browser: Chrome/Firefox/Safari

**Comment by arfedulov** [comment]
Yes, that was a desired behavior. Want to make a PR for this?

**Comment by syntext** [comment]
Sure, I added the feature to choose between types of behavior as you can see here

https://github.com/syntext/semantic-ui-calendar-react/commit/0a96c699022779a95b3e44a50c5363528bba79e6

Although I can build and see my change works, I'd like to write some proper tests for it but I when I run 'yarn test' it complains about an unexpected token in {allowJs:true}. Could you perhaps explain in a few words how to set up my environment properly? Apparently 'yarn install' isn't sufficient. Near zero TS experience here 😄

**Comment by arfedulov** [comment]
I was struggling with this line ``TS_NODE_COMPILER_OPTIONS=\"{\"\"allowJs\"\":true}\"`` too once. I was just experimenting and found a configuration that works. I don't understand why it doesn't work now. 

As a quick solution you can try the following:

* change allowJs to ``true`` in tsconfig.json at project root
* change test command in package.json to this ``"test": "npx mocha -r ts-node/register ./test/setup.js ./test/**/*.{js,jsx,ts,tsx}"``

Try ``yarn test`` again.

**Comment by syntext** [comment]
Thanks! Perfect solution, I've created a pull request.

Btw, I noticed the tests in inputs/pickers/dayPicker don't run when using yarn to execute all the tests at once. You might want to change `./test/**/*.{js,jsx,ts,tsx}` to `./test/**/**/*.{js,jsx,ts,tsx}`

**Comment by arfedulov** [comment]
How about using recursive flag ``npx mocha -r ts-node/register --recursive ./test/setup.js ./test``? On my machine all of the variants work equally well with ``npm run test`` and ``yarn test``.

**Comment by arfedulov** [comment]
PR merged
