### ISSUE TITLE
DateInput popup still occurs when readOnly is true

### ISSUE THREAD

**Issue by zheyujie** [arfedulov/semantic-ui-calendar-react#107]
DateInput popup still occurs when readOnly is true. The field cannot be editted manually when readOnly is true, but it can still be editted by selecting a date in popup. Is this the expected behavior?

Thanks

**Comment by arfedulov** [comment]
It's a bug. Thanks for report :+1:

**Comment by arfedulov** [comment]
Fixed in fe63e3d35c22b62ef23511afba47f56346d03187 . Popup doesn't occur if input has ``readOnly == true`` prop.

**Comment by zheyujie** [comment]
Thanks for the quick update :-)
