### ISSUE TITLE
Suboptimal work on mobile

### ISSUE THREAD

**Issue by tailhook** [arfedulov/semantic-ui-calendar-react#108]
When I click on input field on mobile phone, the following happens:
1. Calendar pops up
2. In a fraction of second, screen keyboard appears, making calendar position off the screen rendering calendar unusable

**Expected behavior**

Don't show screen keyboard and popup calendar both at the same time. (probably show screen keyboard on an extra click, or don't show at all?)

**Dependencies versions**

* semantic-ui-react 0.85.0
* semantic-ui-css (or any alternative) 2.4.1
* semantic-ui-calendar-react 0.14.2

**Comment by arfedulov** [comment]
Yes, this is a problem.

**Comment by tailhook** [comment]
Are there any plans for that? Have you already researched the topic? (i.e. is it easily possible or a way too hard?)

**Comment by arfedulov** [comment]
I haven't research yet. Can't promise anything yet.

**Comment by alexbussan** [comment]
I've been experimenting with making the calendar have inline={true} when the size of the viewport is small enough for mobile. I'm not yet sure how to read the value form the inline calendar though

**Comment by arfedulov** [comment]
@alexbussan You can read the value using ``onChange`` callback (exactly the same way like with not-inline one).
```js
(event, {value}) => { ... };
```

**Comment by jav974** [comment]
With the 0.14.2 version (don't know about 0.14.3 but for sure 0.14.4 doesn't work with that trick), you can specify readOnly={true} to DateInput widget in order not to show the keyboard on mobile devices when entering the input.

In the latest version 0.14.4 calendar doesn't pop up when field is readOnly.

**Comment by arfedulov** [comment]
Added ``hideMobileKeyboard`` prop #143. It uses that hack with ``readonly`` attribute. Seems like it works.

```tsx
  <DateInput
    ...
    hideMobileKeyboard
  />
```

**Comment by DannyHinshaw** [comment]
@arfedulov This behavior is still unfortunately occurring, using v0.15.3. 

Have tested on a Galaxy S9 and Pixel 2 and it happens for both targets.

My `DatePicker` looks like so:

```typescript
<DateInput name="date" dateFormat="MM-DD-YYYY" placeholder="Date"
    value={props.formData.date} iconPosition="left" disable={BLACK_OUT_DATES}
    hideMobileKeyboard={true} popupPosition="top center" type="date"
    onChange={handleInputChange} error={props.formErrors.dateError} />;
``` 
Am I missing something?

**Comment by DannyHinshaw** [comment]
For any others trying to get this to work here's my hooks implementation:
```typescript
	// Try to disable keyboard from popping over datepicker on mobile.
	useEffect(() => {
		const datePickers = document.querySelectorAll("[name=\"date\"]");

		// @ts-ignore
		[...datePickers].forEach((el => {
			const currPicker = el as HTMLInputElement;
			currPicker.setAttribute("readonly", "true");
		}));
	}, []);
```

If you're using classes you can just throw that into the `componentDidMount` lifecycle method.

**Comment by iamdevlinph** [comment]
The `hideMobileKeyboard` doesn't also seem to work on my end. I've created an issue for it #179 

Edit: Closed related ticket due to end-user error
