### ISSUE TITLE
Calendar does not fit in Popup

### ISSUE THREAD

**Issue by chrisss404** [arfedulov/semantic-ui-calendar-react#11]
Hi,

I am using [semantic-ui-react](https://www.npmjs.com/package/semantic-ui-react) with styles from [semantic-ui-less](https://www.npmjs.com/package/semantic-ui-less) including the provided calendar.css. However there is a max width on the popup element within semantic-ui-less causing issues.

The following screenshot shows the current DateInput popup:
![before](https://user-images.githubusercontent.com/980871/40836478-2dcdc008-6597-11e8-9b46-8355a6ca1c67.png)

When I remove the max width by applying 

    .ui.popup.suir-calendar {
      max-width: none;
    }

the calendar fits into the popup, but it causes positioning issues, as can be seen in this screenshot
![after](https://user-images.githubusercontent.com/980871/40836491-3619e3fe-6597-11e8-894f-5ab41febf02e.png)

Is it better to remove the max-width from the popup element or to reduce the width of the calendar?

Thanks for your effort on this project & best regards
Christian

**Comment by arfedulov** [comment]
In what browser you have experienced this issue?

I've seen that popup's content sometimes goes beyond popup's border on IE.
Setting `.suir-calendar.popup { max-width: none }` solves it.

The only case where I've run into a problem where popup goes outside of a viewport is when viewport sizes was too small to contain a popup. In that case I think the most appropriate solution is using inline version of a component.

**Comment by chrisss404** [comment]
I found a solution to this issue, you have to add the property `flowing` to CustomPopup.

> ### Flowing 
> A popup can have no maximum width and continue to flow to fit its content.
https://react.semantic-ui.com/modules/popup#variations-flowing
