### ISSUE TITLE
Types no longer working

### ISSUE THREAD

**Issue by tomitrescak** [arfedulov/semantic-ui-calendar-react#113]
**Describe the bug**

Since version 0.14.1 the types are no longer working.

Your types point to 'dist/index.d.ts' which is not present.
As a result all TS compilations now fail ;(

**Comment by arfedulov** [comment]
fixed #115

**Comment by brian-ttc** [comment]
is this fix available on npm yet?

**Comment by arfedulov** [comment]
Not yet.

**Comment by arfedulov** [comment]
published
