### ISSUE TITLE
[Feature Request] "Year and Month" date picker

### ISSUE THREAD

**Issue by MarkAZhang** [arfedulov/semantic-ui-calendar-react#114]
Right now you can pick a year (2018), pick just a month (Jan), or pick a full date (2018-01-01). I'd like to be able to pick a date at the month-level (2018-01). So you'd pick the year, pick the month, and then the datepicker would close and the date would return.

Would love your thoughts on how to best make this change (for example, should i modify MonthPicker or DatePicker?). Happy to submit a PR.

**Comment by arfedulov** [comment]
What if we just add some prop to  ``DateInput`` that will force it to return value after selecting just year and month? look at this method https://github.com/arfedulov/semantic-ui-calendar-react/blob/37bffcd574d428d3de7f901bf9a1d97c1a26ba42/src/inputs/DateInput.tsx#L332

**Comment by MarkAZhang** [comment]
Sounds great. Will submit PR.

**Comment by MarkAZhang** [comment]
We ended up working around the issue, so no longer need this feature. Closing the issue for now.

**Comment by matiasdg** [comment]
Hey @MarkAZhang how did you solve the issue?
