### ISSUE TITLE
Invalid output date format

### ISSUE THREAD

**Issue by theochampion** [arfedulov/semantic-ui-calendar-react#116]
Hi,

I'm trying to use this component for a datetime range selection but I'm running into a problem.

The value sent to the `onChange` handler is in the `DD-MM-YYYY HH-mm` format, which can't be parsed by the `Date` object constructor and therefore return the current time instead.

here is the code I use to convert back to `Date` object on change
```javascript
  _handleTimeChange = (e, { name, value }) => {
    console.log("str value: " + value);
    console.log("date value: " + Date(value));

    this.setState({ [name]: Date(value) });
  };
```

and the output 

```
str value: 20-03-2019 18:40
date value: Mon Mar 25 2019 16:11:13 GMT+1100 (Australian Eastern Daylight Time) // current time
```

As you can see, the selected date can't be parsed by the `Date` object which result in the wrong time being updated.

Is there a way to modify the date string format used or use a `Date` object instead alltogether ?

Thanks !

**Comment by arfedulov** [comment]
There is  a ``dateTimeFormat`` prop on DateTimeInput. You can set proper output format via this prop.
For example ``dateTimeFormat='YYYY-MM-DD HH:mm'``.
