### ISSUE TITLE
Passing a label with a content won't work

### ISSUE THREAD

**Issue by UnclePetros** [arfedulov/semantic-ui-calendar-react#119]
I want to report this misbehaviour/feature.
When I try to pass a label to the DateInput in this way:
`label = {{ content: 'LabelName'}}`

It won't work.
The same work on a standard Input SUIR component.

May be a SUIR version compatibility issue?

My Semantic UI React version is: 0.86.0
Version of this module is: 0.14.3

Thank you for this needed module/plugin.

Regards
Pietro

**Comment by arfedulov** [comment]
I guess it's because we use ``Form.Input`` in this module for input elements. ``label`` prop behaves differently on that component. Whether to use ``Form.Input`` or ``Input`` it's a whole other story. Probably it would be convenient to be able to customize underlying input component.

**Comment by UnclePetros** [comment]
Well, thank you for the quick answer.
I have no idea of the cause; what I can say I have the same problem also on a dropdown SUIR component (normal label work, label with content property does not).
Yes, It would be great if possible to customize the sub input component.
At the moment I've solved using a separate Label component and adding a specific css class to look like an Input with content label (It looks pretty well).
Thank you again for sharing your work.

Regards
Pietro
