### ISSUE TITLE
DateTimeInput disabled prop support?

### ISSUE THREAD

**Issue by dehypnosis** [arfedulov/semantic-ui-calendar-react#13]
Thank you for your hard work!!!

I think `disabled` prop will be very helpful!

**Comment by dehypnosis** [comment]
This situation was due to Input Components' `componentShouldUpdate` method. I made a PR.

**Comment by tailhook** [comment]
Is it fixed? Can't find disabled property in commit or docs.

**Comment by arfedulov** [comment]
@tailhook I cant remember what was this issue about :sweat_smile: . I document the whole interface in readme. So if you cant find something in there then it is not implemented.

**Comment by tailhook** [comment]
Well, I think it's about "disabled" property, which doesn't allow to change input (and perhaps doesn't show calendar). Alternatively, there is no readOnly property too.

Should we reopen this issue or just create a new one?

**Comment by arfedulov** [comment]
Better create a new one.

**Comment by cristiangabor** [comment]
Is disabled property fully supported now ? I have a situation where i set disabled={true} but under some circumstances DateInput is not disabled
