### ISSUE TITLE
Feature request : Change langage

### ISSUE THREAD

**Issue by DamienArmillon** [arfedulov/semantic-ui-calendar-react#145]
Hello,
Is it possible to add an option to change the language of the calendar ? Not saying to hardcode for every single language, but at least to allow us to give a list of custom months and day in props.
Thank you !

**Comment by arfedulov** [comment]
https://github.com/arfedulov/semantic-ui-calendar-react#locales-support

Doesn't these work?

**Comment by DamienArmillon** [comment]
Oh well, I'm sorry ! I though it was just for different format ! Thanks you !
