### ISSUE TITLE
Calendar crashes when set maxDate in DateInput

### ISSUE THREAD

**Issue by nscodelover** [arfedulov/semantic-ui-calendar-react#149]
**Describe the bug**
Calendar crashes when paste certain date by keyboard to DateInput if its maxDate is set.
If set the maxDate to today and paste the certain date that greater than this month, calendar crashes.

**To Reproduce**
1. copy and paste '06/01/2019' to input box
2. Click on any other elements
3. Click on the input box that pasted the date

**Expected behavior**
Should not happened any crashes.

**Screenshots**
![Screen Shot 2019-05-09 at 9 55 40 PM](https://user-images.githubusercontent.com/25214541/57479149-7505de80-72a5-11e9-8140-4b1591535c6e.png)

**Dependencies versions**
Provide version numbers of following packages:
* semantic-ui-react: "^0.85.0",
* semantic-ui-css (or any alternative): "^2.4.1",
* semantic-ui-calendar-react: "^0.14.2",

**Comment by arfedulov** [comment]
duplication #127
