### ISSUE TITLE
Close the calendar on date select

### ISSUE THREAD

**Issue by whitebyte** [arfedulov/semantic-ui-calendar-react#15]
Sorry for the dumb question, but how can we close the widget on date select event, as it does for default non semantic-ui widgets (e.g. Firefox's `<input type='date'>`)?

**Comment by arfedulov** [comment]
It's not implemented yet. In mdehoog's [semantic-ui-calendar](https://github.com/mdehoog/Semantic-UI-Calendar#settings) there is a `closable` option. If it set to `true` popup closes on selecting date/time. I'm going to implement same behaviour here.

**Comment by whitebyte** [comment]
Wow, that wast fast. Thanks much!
