### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by ipnuds** [arfedulov/semantic-ui-calendar-react#150]
while access page that has calendar via url (server side) there's error 
ReferenceError: navigator is not defined on checkMobile.js:5:5

if I access that page via link react-routers (client side) it's work

using semantic-ui-react 0.87.1;

**Comment by arfedulov** [comment]
Thanks for report! I'll fix it.

**Comment by DannyHinshaw** [comment]
Also seeing this error, but for some reason it's happening during webpack build for production in a Gatsby site.

**Comment by minkasu-kuppusamy** [comment]
is it fixed ???

**Comment by DannyHinshaw** [comment]
No, but forked and built with a patch. I was gonna pr it but there are unrelated broken unit tests in the project as that I didn't/don't have time to fix

**Comment by arfedulov** [comment]
@DannyHinshaw make a pr with broken unit tests.
