### ISSUE TITLE
Invalid Date from the value returned

### ISSUE THREAD

**Issue by claeusdev** [arfedulov/semantic-ui-calendar-react#153]
I've been trying to get the date value but the `23-05-2019` format is invalid. 

- tried working to convert it with `moment`, didnt work,

- tried with `new Date("23-05-2019"), also still returns invalid date.

anyone else faced this? Any reason why?

**Comment by arfedulov** [comment]
Default date format is "DD-MM-YYYY". You can chage it by setting ``dateFormat`` prop on DateInput component.

```jsx
<DateInput
    ....
    dateFormat="YYYY-MM-DD"
/>
```
"YYYY-MM-DD" format shold be parsed correctly by ``moment`` and by ``Date``.

The other option is to parse the value using moment and providing optional ``format`` argument: ``moment("23-05-2019", "DD-MM-YYYY")``

**Comment by claeusdev** [comment]
@arfedulov hey worked like a charm. Thanks very much.. i can close this issue now
