### ISSUE TITLE
Not working under react15?

### ISSUE THREAD

**Issue by linrongbin** [arfedulov/semantic-ui-calendar-react#16]
Fragment is used...
bundle.js:13085 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `DatesRangePickerContent`.
    in DatesRangePickerContent (created by DatesRangeInput)
    in table (created by Table)
    in Table (created by DatesRangeInput)
    in div (created by Popup)

**Comment by arfedulov** [comment]
It doesn't use ``React.Fragment`` anymore. Should work now.
