### ISSUE TITLE
DatePicker: how to set initial, min & max value?

### ISSUE THREAD

**Issue by phattv** [arfedulov/semantic-ui-calendar-react#17]
DatePicker: how to set initial, min & max value?

**Comment by arfedulov** [comment]
These are the attributes that still need to be implemented:
``initialDate``: date to display initially when no date is selected
``minDate``: minimum date/time that can be selected, dates/times before are disabled
``maxDate``: maximum date/time that can be selected, dates/times after are disabled

I'll do it soon probably.

**Comment by arfedulov** [comment]
``initialDate`` is available now.

**Comment by anjapadu** [comment]
Great work on this repo.!
Btw initialDate does not work for me. Maybe im doing something wrong?
```
 <DateInput
                                initialDate={"1990-01-01"}
                                name="birth"

                                placeholder="Fecha de nacimiento"
                                popupPosition={"bottom center"}
                                dateFormat={"DD/MM/YYYY"}
                                value={this.state.defaultData.birth}
                                iconPosition="left"
                                onChange={(_e, { value }) => this.setState({
                                    defaultData: {
                                        ...this.state.defaultData,
                                        birth: value
                                    }
                                })}
                            />
```

**Comment by arfedulov** [comment]
@anjapadu are you sure you use the latest version of this module? Currently it's 0.7.0 and it isn't published on npm yet.

**Comment by arfedulov** [comment]
``initialDate``, ``minDate`` and ``maxDate`` are all implemented now. See [readme](https://github.com/arfedulov/semantic-ui-calendar-react/blob/master/README.md) for more info.

**Comment by sdelvalle57** [comment]
initialDate, minDate and maxDate not working on 0.9.0-alpha

<DateInput
                        dateFormat="YYYY/MM/DD"
                
                        iconPosition="left"
                        name="start"
                        maxDate="2018/08/28"
                        disabled = {!isOwner}
                        value={datesRange.start.text}
                        onChange={this.handleChange} />

tried:  maxDate="2018/08/28",  maxDate="2018-08-28", maxDate="08-28-2018"

**Comment by arfedulov** [comment]
@sdelvalle57  yes, there is a new issue #31
