### ISSUE TITLE
When initialDate < minDate is getting an error

### ISSUE THREAD

**Issue by ibnukipa** [arfedulov/semantic-ui-calendar-react#183]
**Describe the bug**
When initialDate < minDate is getting an error:
`TypeError: undefined is not an object (evaluating 'selectable[0].position')`

**To Reproduce**
1. set the value or initialDate < minDate

**Expected behavior**
value or initialDate can be lower than minDate

```
if(selectable[0]) return selectable[0].position;
else null;
```
or use optional chaining

**Dependencies versions**
`"semantic-ui-calendar-react": "^0.15.3"`

**Comment by DovahBrownies** [comment]
@ibnukipa It's mainly because the calendar doesn't even render the days that come before `minDate`. So this is expected behavior...
