### ISSUE TITLE
Malformed form

### ISSUE THREAD

**Issue by HoatPro** [arfedulov/semantic-ui-calendar-react#187]
**Describe the bug**
I want to choose the right format as default
**Screenshots**

<img src="https://i.imgur.com/pqmVphL.png" />
but my format is:
<img src="https://i.imgur.com/1zhoLPA.png" />

**Dependencies versions**
Provide version numbers of following packages:

* semantic-ui-react
* semantic-ui-css (or any alternative)
* semantic-ui-calendar-react

**Comment by DovahBrownies** [comment]
@HoatPro - Are you sure you're not forcing any styles on the calendar? This kind of looks like you changed the `display` style.

Just for reference, the style for the calendar should be `display: table;`. Try adding that to the calendar's style and let me know if that fixes the issue for you. If it does, then you're forcing the `display` to be different in your styles.

**Comment by HoatPro** [comment]
> @HoatPro - Are you sure you're not forcing any styles on the calendar? This kind of looks like you changed the `display` style.
> 
> Just for reference, the style for the calendar should be `display: table;`. Try adding that to the calendar's style and let me know if that fixes the issue for you. If it does, then you're forcing the `display` to be different in your styles.

Thank you very much, i fixed it.
