### ISSUE TITLE
Is this package no longer being maintained?

### ISSUE THREAD

**Issue by cam31007** [arfedulov/semantic-ui-calendar-react#189]
No really a bug to report, just wondering if there are further plans to continue maintaining this package? It has been almost 6 months since the last code merge. I just want to figure if it's worth opening pull requests for new features/bugs, or if I should just fork instead.

Thanks!

**Comment by arfedulov** [comment]
It is not maintained. It should get "deprecated" status probably.

**Comment by cam31007** [comment]
Well, that's unfortunate. Thanks for taking the time to respond and everything you did here. Cheers.
