### ISSUE TITLE
Can't Push to Repo?

### ISSUE THREAD

**Issue by DovahBrownies** [arfedulov/semantic-ui-calendar-react#190]
### Not a bug but an issue.

I can't seem to push to repository under a new branch...

```
λ git push origin dots
Enter passphrase for key '/c/Users/Joe/.ssh/id_rsa':
ERROR: Permission to arfedulov/semantic-ui-calendar-react.git denied to DovahBrownies.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Is contributing disabled?

### EDIT
I was able to fork, push to the fork and then PR from there...

**Comment by arfedulov** [comment]
You are trying to push right into original repo (seams like that). Instead, you need to push into your forked repo.

I need to warn though that I dont have time for maintaining this project.
