### ISSUE TITLE
Autocomplete='off' not working

### ISSUE THREAD

**Issue by mpaccione** [arfedulov/semantic-ui-calendar-react#196]
Hello i'm on Windows Chrome and autocomplete='off' is not working

This causes the already entered text to appear above the time popups... making it impossible to select.

Can you please fix this!

**Comment by mpaccione** [comment]
![image](https://user-images.githubusercontent.com/8552642/79528427-c6bef900-801e-11ea-9559-8c30c9574f52.png)

**Comment by mpaccione** [comment]
I've had to get around this via this solution...

```
	// Remove all autocompletes
	useEffect(() => {
		Array.from(document.querySelectorAll('input')).forEach((input, index) => {
			input.setAttribute('autocomplete', 'off')
		})
	}, [schedulingSession])
```

**Comment by EddieDe** [comment]
@mpaccione try to use `autoComplete` react property instead of `autocomplete` html property.
`<TimeInput autoComplete="off" />`
https://reactjs.org/docs/dom-elements.html#all-supported-html-attributes
