### ISSUE TITLE
Plans to support month/year picker?

### ISSUE THREAD

**Issue by phillbaker** [arfedulov/semantic-ui-calendar-react#2]
Thanks for porting the mdehoog/Semantic-UI-Calendar to react! 👍 

Do you have any plans to support clicking on the month to "zoom out" and support months/years? I believe the mdehoog version supports this via a [`mode` which can be also be year and month](https://github.com/mdehoog/Semantic-UI-Calendar/blob/master/src/definitions/modules/calendar.js#L1006)

For example: 
![](https://user-images.githubusercontent.com/1854141/32366949-a769182a-c080-11e7-84f8-5b5de7c1ceec.png)

![](https://user-images.githubusercontent.com/1854141/32366965-b904019e-c080-11e7-88c2-3e78b2057864.png)

**Comment by arfedulov** [comment]
Yes, i have these plans. I want to provide a functionality equal to mdehoog version.

**Comment by arfedulov** [comment]
I think it's solved in a3bbfc24aa231c3bdc550feb481148ab91265a4c

**Comment by phillbaker** [comment]
👍 Much appreciated! We'll try it out.

**Comment by Rombusevil** [comment]
Hey @arfedulov is there a way to get only year/month picker and avoid selecting a day?

**Comment by arfedulov** [comment]
@Rombusevil no, for now there is only one way to do this - using year and month inputs separately.

**Comment by DovahBrownies** [comment]
Sorry @arfedulov , but I'm kind of confused on how to set the `DateInput` to only take month or year inputs. Some help, please?

**Comment by arfedulov** [comment]
Unfortunately it's impossible yet. #66

**Comment by cbrianbet** [comment]
Any progress made on this please
