### ISSUE TITLE
DateInput Flicker in .tsx 

### ISSUE THREAD

**Issue by kkakroo** [arfedulov/semantic-ui-calendar-react#201]
**Describe the bug**
When we use DateInput in .tsx files and try to fix the flicker of the calendar with [this](https://stackoverflow.com/questions/57618248/why-datepicker-flicker-in-react-when-focus-in-input-field) fix, we get a compile-time error.

**To Reproduce**
1. Go to https://codesandbox.io/s/semantic-ui-calendar-reactissue-6mzgf
2. App1.tsx and App.js can be switched in index.js
3. If we wait for a while we see the error `Type 'false' is not assignable to type 'SemanticTRANSITIONS'` in App1.tsx `animation` property.

If there is any other fix for the flickering, please let me know.

**Expected behavior**
Flickering should not happen

**Screenshots**
NA

**Dependencies versions**
Provide version numbers of following packages:

"semantic-ui-calendar-react": "0.15.3",
"semantic-ui-css": "2.4.1",
"semantic-ui-react": "0.88.2"

**Comment by kkakroo** [comment]
Tried to set the `duration` property to 0. This works without the `animation` fix when there is one DateInput, but I have multiple controls on the page if one of them is open and I open another one, the second one flickers.

**Comment by deamwork** [comment]
dup, reference: #152

**Comment by kkakroo** [comment]
Thanks @deamwork 
Fixed this issue by wrapping the DateInput inside a js component and consuming that component from the tsx file.

Set animation={''} for fixing the issue as animation={false} gives console errors.
