### ISSUE TITLE
closable DateTime also closes modal 

### ISSUE THREAD

**Issue by ayanez17** [arfedulov/semantic-ui-calendar-react#27]
When you have a DateTimeInput within a modal and once you finish selecting a date & time the closable attribute also closes the modal itself. 

relevant code: 

```
        <Modal trigger={<Button>Show Modal</Button>} }>
          <Modal.Header>Select a Photo</Modal.Header>
          <Modal.Content>
            <Modal.Description>
              <DateTimeInput
                fluid
                closable
                label='Time and Date'
                name="dateTime"
                placeholder="Date Time"
                iconPosition="left"
              />
            </Modal.Description>
          </Modal.Content>
        </Modal>
```

**Comment by arfedulov** [comment]
This is happening probably because we have here Portal inside a Portal. And the one inside somehow affect that is outside.

**Comment by ayanez17** [comment]
As a work around  you can do the following: 
1) add attribute  `closeOnDimmerClick = {false}` to the modal
2) Add attribute `closeIcon` to the modal
When you set `closeOnDimmerClick` to false you would need to use the `esc` key to leave the modal so to avoid that you can just add a closeIcon button with (2)

**Comment by arfedulov** [comment]
Seems like this issue is gone starting with *semantic-ui-react* version 0.82.1. And don't forget to use version 2.3 of *semantic-ui-css*.

**Comment by funewik** [comment]
Hello,

I can confirm that it's still an ongoing problem :
https://codesandbox.io/s/2v1l219nwj

Thanks in advance or help.
