### ISSUE TITLE
is it possible to turn autocomplete off?

### ISSUE THREAD

**Issue by amcculloughflexera** [arfedulov/semantic-ui-calendar-react#29]
Is it possible to turn the autocomplete off on the input tag of the date picker?  The autocomplete is hiding part of the calendar popup (Chrome Version 68.0.3440.106)

![image](https://user-images.githubusercontent.com/37803443/44284199-b0b0d200-a258-11e8-9d70-876ce625e2a4.png)

**Comment by arfedulov** [comment]
Yes, I see. I'll try to figure out something.
@amcculloughflexera may be you found some workaround already?

**Comment by arfedulov** [comment]
I think I found a solution. Set ``autoComplete="off"`` on your input component. Like this:
```jsx
<DateInput autoComplete="off" />
```
And note a camel case, it matters.
