### ISSUE TITLE
minDate params not working

### ISSUE THREAD

**Issue by kn4rfy** [arfedulov/semantic-ui-calendar-react#31]
I used this `minDate={moment(new Date())}` but it's not working

**Comment by sdelvalle57** [comment]
is not working mate, u should check

**Comment by sdelvalle57** [comment]
Not all these are working, maxDate, minDate, initialDate    
    <DateInput
                    dateFormat="YYYY/MM/DD"
                    iconPosition="left"
                    name="start"
                    maxDate="2018/08/28"
                    disabled = {!isOwner}
                    value={datesRange.start.text}
                    onChange={this.handleChange} />
tried: maxDate="2018/08/28", maxDate="2018-08-28", maxDate="08-28-2018"

**Comment by chenmargalit** [comment]
<DateInput
                            dateFormat="YYYY/MM/DD"
                            maxDate="2019/07/07"


Not making any effect at all ...

**Comment by arfedulov** [comment]
@chenmargalit I tried this and seems like it works.

```tsx
<DateInput
          placeholder='Date'
          popupPosition='bottom right'
          className='example-calendar-input'
          name='date'
          closable
          clearIcon={(<Icon name='remove' color='red' />)}
          clearable={clearable}
          animation='scale'
          duration={200}
          hideMobileKeyboard
          dateFormat='YYYY/MM/DD'
          maxDate='2019/07/07'
          value={this.state.date}
          iconPosition='left'
          preserveViewMode={false}
          autoComplete='off'
          onChange={this.handleChange}
        />
```

![image](https://user-images.githubusercontent.com/19156819/60691485-9f0c0380-9ed8-11e9-9d02-fbd6574b232b.png)

**Comment by chenmargalit** [comment]
@arfedulov  thanks. What versions are u using ? of the react/semantic ui react/semantic ui calender/ react? cause for some reason the same code doesnt work on my machine

**Comment by chenmargalit** [comment]
@arfedulov most of it is working, from what I checked and not working are the min/max date and the disable/enable

**Comment by arfedulov** [comment]
I don't think it's somehow related to *react* or *semantic-ui-react*. I tested this on semantic-ui-calendar-react@0.15.0 and semantic-ui-react@0.86.0.

Try using default date format. Does `minDate`/`maxDate` work after that?

**Comment by chenmargalit** [comment]
@arfedulov  what do u mean with default ? 
           <DateInput
                            maxDate="2019/07/07"
                            pickerStyle={{
                                backgroundColor: "#ff725d",
                                color: "white"
                            }}
                            name="date"
                            placeholder="Date"
                            value={this.state.date}
                            onChange={this.handleChange}
                            inline
                        />

this doesnt work

**Comment by arfedulov** [comment]
Default format is `DD-MM-YYYY`. If you omit `dateFormat` prop the default is used and you have to provide `maxDate` or `minDate` in that format too.

Your last example should not work. It should work if you add this:

```diff
<DateInput
    maxDate="2019/07/07"
+   dateFormat="YYYY/MM/DD"
    pickerStyle={{
    backgroundColor: "#ff725d",
    color: "white"
    }}
    name="date"
    placeholder="Date"
    value={this.state.date}
    onChange={this.handleChange}
    inline
/>
```

or change this:

```diff
<DateInput
-   maxDate="2019/07/07"
+   maxDate="07-07-2019"
    pickerStyle={{
    backgroundColor: "#ff725d",
    color: "white"
    }}
    name="date"
    placeholder="Date"
    value={this.state.date}
    onChange={this.handleChange}
    inline
/>
```

You also can provide Date or moment to `maxDate` and `minDate`. `maxDate={ moment('2019-07-07') }` or `maxDate={ new Date('2019-07-07') }`.

**Comment by chenmargalit** [comment]
Yea I tried those before as well .. I dont know why but nothing has any kind of effect .. no matter what I tried

          <DateInput
                            dateFormat="YYYY-MM-DD"
                            minDate={moment("2019-07-03")}
                            pickerStyle={{
                                backgroundColor: "#ff725d",
                                color: "white"
                            }}
                            name="date"
                            placeholder="Date"
                            value={this.state.date}
                            onChange={this.handleChange}
                            inline
                        />

![image](https://user-images.githubusercontent.com/33844030/60793936-faecbb80-a168-11e9-9e76-8f3774352db1.png)

**Comment by arfedulov** [comment]
I didnt check yet, but maybe the effect is invisible because of overwriten styles? Try without pickerStyles.

**Comment by chenmargalit** [comment]
not working as well ...

**Comment by arfedulov** [comment]
Can you create interactive example with this bug on codepen or any site like that?

**Comment by chenmargalit** [comment]
a bit packed with work (as I have to write the calendar my self now :)) I'll try to do it when things will cool
