### ISSUE TITLE
(feat) Keyboard shortcut support

### ISSUE THREAD

**Issue by hubertguillemain** [arfedulov/semantic-ui-calendar-react#32]
once the DateTime picker is focused, the table appears below in a popup, but the user ca'nt use keyboard navigation (typically arrows/enter/space) to navigate (see how it's done in the jQuery initial implementation)

It would be great to have keyboard support to make this component accessible

**Comment by arfedulov** [comment]
Yeah, this definitely should be implemented.

**Comment by arfedulov** [comment]
Working on it.

**Comment by arfedulov** [comment]
Solved in 0033d62a8061c3cd1d2d9ff0fad7b0e17b0167a2
