### ISSUE TITLE
Calendar pop-up closes on month selection if displayed on top of field

### ISSUE THREAD

**Issue by zarko** [arfedulov/semantic-ui-calendar-react#34]
If pop-up calendar is displayed above input field, it closes automatically if user tries to pick month by clicking on month name.

https://react-e1y1ed.stackblitz.io

**Comment by arfedulov** [comment]
Could you please provide version numbers of these packages:

* semantic-ui-react
* semantic-ui-css
* semantic-ui-calendar-react

**Comment by zarko** [comment]
Sure, 

this is editable StackBlitz, so it has version numbers https://stackblitz.com/edit/react-e1y1ed

semantic-ui-react: 0.80.2
semantic-ui-css: 2.2.12
semantic-ui-calendar-react: 0.8.0

**Comment by arfedulov** [comment]
fixed in version 0.9.0
