### ISSUE TITLE
Calendar pop-up closes on month selection

### ISSUE THREAD

**Issue by remingtonlang** [arfedulov/semantic-ui-calendar-react#43]
**Describe the bug**
Calendar pop-up closes on month mouseover. Similar or a regression of #34.I'm able to reproduce the original reported behavior using version 0.10.0 with Semantic 0.83.0. Reverting back 0.81.1 resolves this behavior so something between these two versions causes the calendar to close on hover

**To Reproduce**
1. https://react-e1y1ed.stackblitz.io

**Expected behavior**
Mousing over the calendar should not close randomly, but close on selection

**Dependencies versions**
Provide version numbers of following packages:
    "semantic-ui-calendar-react": "^0.10.0",
    "semantic-ui-css": "^2.4.1",
    "semantic-ui-react": "0.83.0",

**Comment by eCorke** [comment]
Would be great, if it could be fixed, but officially version 0.83.0 is not supported (semantic-ui-react@<=0.80.2).

**Comment by remingtonlang** [comment]
I missed that dependency on version, thanks @eCorke

**Comment by arfedulov** [comment]
What about a semantic-ui-react version <=0.80.2, to be honest, I just forgot to delete this restriction. There was some other issues with semantic-ui-react greater than 0.80.2 but they was solved in later versions.

@remingtonlang I can't open your example (the page doesn't load for some reason). But I reproduced the bug. Seems like it starts from semantic-ui-react@0.83.0.

**Comment by arfedulov** [comment]
*semantic-ui-react* v0.84.0 was released a few days ago. It works with that version.
