### ISSUE TITLE
Year Picker key out/in on input , picker is not opening /closing

### ISSUE THREAD

**Issue by gopeshjangid2** [arfedulov/semantic-ui-calendar-react#44]
**Describe the bug**

when i was planning to use this picker  , i found 2 issues in it.

1.  When i go to the year picker by key navigation , year should be opened  and on press tab/move to next element by key navigation , it should be closed.

2. when i select '2050' year and close it , again i open it , should be there 2050 range years with selected year.

so @arfedulov  can you pls give me solution on these issues ?

how to fix them ?

Thanks
Gopesh

**Comment by arfedulov** [comment]
1. In order to achieve desired behavior I think it's enough to set up popup to close and open on focus (currently it does it on click). But if we set it up to close and open on focus it will close after selecting anything (because when you select a value in calendar input field looses focus). Any thoughts on how to deal with that?

**Comment by arfedulov** [comment]
2. Fixed that in 6c639aa70b53a8c7a56e83c24fdcab8c4aec2aff

**Comment by gopeshjangid2** [comment]
it that focus issue resolved ?

**Comment by arfedulov** [comment]
No yet, only 2050 year issue resolved.

**Comment by gopeshjangid2** [comment]
thanks.....also plz think on that focus issue....i need to add key shortcuts on year picker...like when i manually enter year short value then i get full year from shortcut method and replace that with incomplete year vlaue i.e (00 =>2018) , i want to press tab key and closing picker.

**Comment by arfedulov** [comment]
Yes, I have this issue as a priority.

**Comment by arfedulov** [comment]
It is not published to npm yet. Until it is not published you can clone the github repo and link it  to your project.

**Comment by gopeshjangid2** [comment]
hi, please see the mouse navigation issue. 
thanks

**Comment by arfedulov** [comment]
tab navigation issue is fixed in e3d1807d810c06ff32936ab5c4f3ea4aedf12f53

**Comment by gopeshjangid2** [comment]
@arfedulov  is that fixed issue updated to npm ?
