### ISSUE TITLE
Calendar hide immediately while hover on it

### ISSUE THREAD

**Issue by fiona23** [arfedulov/semantic-ui-calendar-react#46]
**Describe the bug**
Calendar hide immediately while hover on it

**To Reproduce**
1. Go to 'https://stackblitz.com/edit/react-dhk726'
2. Click on 'input'
3. hover on some date

**Dependencies versions**
    "react": "16.6.0",
    "react-dom": "16.6.0",
    "semantic-ui-calendar-react": "0.11.0",
    "semantic-ui-css": "^2.4.1",
    "semantic-ui-react": "0.83.0"

**Comment by jambyung** [comment]
For anyone who is having this issue, try setting `closeOnMouseLeave={false}` and try again. Might not be a expected behaviour but a lot more usable.

**Comment by hyperhtml** [comment]
Likely related to this bug that was just fixed in semantic-ui-react: (https://github.com/Semantic-Org/Semantic-UI-React/pull/3257)

**Comment by fiona23** [comment]
@hyperhtml Thanks a lot!

**Comment by arfedulov** [comment]
This is a duplication #43.

Waiting for new *semantic-ui-react* release.

**Comment by arfedulov** [comment]
Works with *semantic-ui-react* v0.84.0
