### ISSUE TITLE
Question regarding compatibility warning to semantic ui react 0.83.0

### ISSUE THREAD

**Issue by flq** [arfedulov/semantic-ui-calendar-react#53]
Hi there,
you explicitly warn that there are compatibility issues with semantic 0.83 - could you please state the nature of the compatibility emergency? ;) Can I help?

Regards
Frank

**Comment by arfedulov** [comment]
Hi! There is only one issue relating to 0.83.0 but it is huge. Take a look at these threads #43 #46. And it seems like there is a PR already made in *semantic-ui-react* but it is not released yet.

**Comment by flq** [comment]
Ok - any idea which PR it is so it can be referenced here?

**Comment by arfedulov** [comment]
*semantic-ui-react* v0.84.0 is released.
