### ISSUE TITLE
Popup closing before selection, minDate not checking minutes, No option to resize the popup

### ISSUE THREAD

**Issue by krajasekhar** [arfedulov/semantic-ui-calendar-react#54]
**- Popup closing before selection**
  When I move the mouse cursor out of text field to the calendar, the popup is getting disappeared even before the value is selected.
However I have avoided this by passing these parameters
```
closeOnMouseLeave={false}
closable={true}
```
**- minDate not checking minutes.**
  I have given the parameter `minDate as {new Date()}` but it is allowing me to select values belonging to the current hour but minutes before the current time.
For example:At time 14:30, selecting 13:55 is not possible but 14:05 is possible which should by disabled.

**- No option to resize the popup**
 Calendar popup is appearing big in small screens and not able to reduce. Require some option to pass style the Popup which is the children.

Code available at https://stackblitz.com/edit/raju-semantic-issue?file=index.js 

Dependancy versions:
react16.5.0
react-datepicker2.0.0
react-dom16.5.0
semantic-ui-calendar-react0.12.1
semantic-ui-css2.4.1
semantic-ui-react0.83.0

**Comment by arfedulov** [comment]
#### Popup closing before selection
Duplication #46 #43

#### minDate not checking minutes
It's fair. I will work on it.

#### No option to resize the popup
I will check possible solutions to this problem.

**Comment by arfedulov** [comment]
### popup is closing before selection

Semantic-ui-react@0.84.0 released a few days ago. Use this version to avoid this bug.

### resizable popup

Not yet. Before solving this I'm going to clean up a project a little bit. Unfortunately I have very little time.

**Comment by krajasekhar** [comment]
The above are fine, I am waiting for fix to 'minDate not checking minutes'

**Comment by arfedulov** [comment]
Already done it. It will be available in next release.

**Comment by krajasekhar** [comment]
'minDate not checking minutes' 
Now the passed minutes of the current hour are hidden well but the problem is the same minutes got hidden in every other hour.

Ex: Suppose the current time is 06:30, as expected minutes from 00 to 30 are hidden inside '6th' hour but unexpectedly 00 to 30 are hidden in '7th' hour as well. Can't select 07:15 now. Please check
