### ISSUE TITLE
No one calendar(Date picker , Year , month) is working on Internet Explorer 11

### ISSUE THREAD

**Issue by gopeshjangid2** [arfedulov/semantic-ui-calendar-react#55]
**Describe the bug**

**To Reproduce**
1. Go to '.live example..'
2. Click on '.on any date picker...'
4. See error   => date will not be selected

@arfedulov 

No one calendar is working on internet explorer 11.

I have checked even your live example on internet explorer. None of them is working on that.

Please fix it as soon as possible. this is issue in my live build.

Thanks
Gopesh

* semantic-ui-react
* semantic-ui-css (or any alternative)
* semantic-ui-calendar-react

**Comment by arfedulov** [comment]
Yeah, I see.

**Comment by arfedulov** [comment]
This issue is introduced with version 0.12.

**Comment by jjavierdguezas** [comment]
hi, first thanks for this repo. there is any update about this issue?

**Comment by arfedulov** [comment]
Not yet. Would be great if somebody help with it.

**Comment by arfedulov** [comment]
I opened an [issue](https://github.com/Semantic-Org/Semantic-UI-React/issues/3365) for this in semantic-ui-react.

**Comment by layershifter** [comment]
`semantic-ui-react@0.85.0` with the fix was released 🎉

**Comment by arfedulov** [comment]
fixed in #110

**Comment by gopeshjangid2** [comment]
@arfedulov  after installed 14.4 it  is showing  Generic type 'SyntheticEvent' requires between 0 to 1 type arguments error.  Please help it.
