### ISSUE TITLE
React does not recognize the `displayWeeks` prop on a DOM element.

### ISSUE THREAD

**Issue by krajasekhar** [arfedulov/semantic-ui-calendar-react#56]
I have not given any prop like 'displayWeeks' for DateTimeInput component but while selecting the value from the popup, exactly after selecting the hour I am getting the below warning in the console.

Warning: React does not recognize the `displayWeeks` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `displayweeks` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in table (created by Table)
    in Table (created by Calendar)
    in Calendar (created by HourView)
    in HourView (created by HourPicker)
    in HourPicker (created by InputView)
    in div (created by Popup)
    in Ref (created by PortalInner)
    in PortalInner (created by Portal)
    in Portal (created by Popup)
    in Popup (created by InputView)
    in InputView (created by DateTimeInput)
    in DateTimeInput (created by App)
    in form (created by Form)
    in Form (created by App)
    in App

Able to simulate this issue in https://stackblitz.com/edit/raju-semantic-issue?file=index.js

Screenshot:
![issue](https://user-images.githubusercontent.com/5477450/49722963-df313d80-fc8b-11e8-893d-853455c9ac8e.PNG)

Dependencies:
react16.5.0
react-datepicker2.0.0
react-dom16.5.0
semantic-ui-calendar-react0.12.1
semantic-ui-css2.4.1
semantic-ui-react0.83.0

**Comment by arfedulov** [comment]
Yes, I've seen this warning too. I accidentally pass that prop down to dom elements. I will remove it in next release.

**Comment by TimMcCauley** [comment]
Greetings @arfedulov - are you planning to fix this? We are using version `0.15` - many cheers!

**Comment by arfedulov** [comment]
Sure, I'll fix it.

**Comment by arfedulov** [comment]
I checked with v0.15.0 and didn't see the warning.
