### ISSUE TITLE
Any plan to support Semantic UI React 0.84?

### ISSUE THREAD

**Issue by zheyujie** [arfedulov/semantic-ui-calendar-react#64]
Just wondering if we are going to support Semantic UI React 0.84 in the near future?

Thanks

**Comment by zheyujie** [comment]
Thanks for the great work, looking forward to seeing it :-)

**Comment by arfedulov** [comment]
Upgraded to 0.84. Seems like it works fine.

**Comment by zheyujie** [comment]
Yep I just tried 0.12.2, working fine now.
Thank you!
