### ISSUE TITLE
Generic type 'SyntheticEvent<T> error

### ISSUE THREAD

**Issue by sivagao** [arfedulov/semantic-ui-calendar-react#68]
**Describe the bug**
pickers/BasePicker.d.ts (81,48): error TS2707: Generic type 'SyntheticEvent<T>' requires between 0 and 1 type arguments.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Dependencies versions**
Provide version numbers of following packages:

* semantic-ui-react
* semantic-ui-css (or any alternative)
* semantic-ui-calendar-react

**Comment by altrang** [comment]
Hello , any news on that issue? I have the same problem

**Comment by arfedulov** [comment]
There is a PR already.

**Comment by arfedulov** [comment]
fixed #69
