### ISSUE TITLE
Invalid date using dateRangeInput on January

### ISSUE THREAD

**Issue by altrang** [arfedulov/semantic-ui-calendar-react#71]
**Describe the bug**
Using DateRangeInput, any date of January is 'invalid-date', its working for any other month

**To Reproduce**
DateRangeInput and try to select a date in january

**Expected behavior**
Just like any other month :)

**Dependencies versions**
Provide version numbers of following packages:

* semantic-ui-react 0.78
* semantic-ui-css (or any alternative) 2.2.12
* semantic-ui-calendar-react 0.9.0-alpha.2

**Comment by jchirik** [comment]
Was this resolved? Im facing the same issue
