### ISSUE TITLE
Generic type 'SyntheticEvent<T> after updating to 0.13

### ISSUE THREAD

**Issue by altrang** [arfedulov/semantic-ui-calendar-react#73]
**Describe the bug**
I still have the same problem after updating to 0.13 

 Generic type 'SyntheticEvent<T>' requires 1 type argument(s) on semantic-ui-calendar-react/dist/pickers/BasePicker.d.ts

**Comment by arfedulov** [comment]
I can't reproduce this. Please provide your typescript configuration. And if possible more context.

**Comment by altrang** [comment]
Here is my package.json

"semantic-ui-calendar-react": "
"semantic-ui-css": "2.4.1",
"semantic-ui-react": "0.81.2",
"typescript": "2.7.2",

here is my tsConfig

`{
  "compilerOptions": {
    "baseUrl": ".",
    "allowSyntheticDefaultImports": true,
    "outDir": "./_build/",
    "sourceMap": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitAny": false,
    "downlevelIteration": true,
    "module": "esnext",
    "target": "es5",
    "lib": ["es2017", "es2017.object", "dom"],
    "jsx": "react",
    "moduleResolution": "node",
    "paths": {
      "app/*": ["app/*"],
      "components/*": ["app/components/*"],
      "assets/*": ["assets/*"]
    },
    "watch": true
  },
  "include": ["./app/**/*"],
  "exclude": ["node_modules"]
}`

**Comment by arfedulov** [comment]
I still can't reproduce it.

**Comment by kdedakia** [comment]
I've run into this issue as well. The problem seems to be with the built`BasePicker.d.ts` file:

```
protected onHoveredCellPositionChange: (e: React.SyntheticEvent<HTMLElement, Event>, { itemPosition }: {
        itemPosition: number;
    }) => void;
```

Removing the Event type argument fixes this issue.

The confusing part is that the `BasePicker.tsx` source file doesn't have this type argument:
```
  protected onHoveredCellPositionChange = (e: React.SyntheticEvent<HTMLElement>,
                                           { itemPosition }: { itemPosition: number }
```

**Comment by arfedulov** [comment]
For some reason compiler inserts default generic types in declaration for ``onHoveredCellPositionChange`` method. I don't understand why it happens. But anyway, inserted types are defaults for SyntheticEvent so why is this a problem?

```tsx
interface SyntheticEvent<T = Element, E = Event> extends BaseSyntheticEvent<E, EventTarget & T, EventTarget> {}
```
