### ISSUE TITLE
Error on build time. Can't resolve 'semantic-ui-react'

### ISSUE THREAD

**Issue by tykko87** [arfedulov/semantic-ui-calendar-react#92]
**Describe the bug**
I install the package, then I import a DateInput. It doesn't let my app because this error occurs during the build time.

./node_modules/semantic-ui-calendar-react/dist/views/InputView.js
Module not found: Can't resolve 'semantic-ui-react' in 'C:\Users\Nicolas\Documents\workspace\crm\client\node_modules\semantic-ui-calendar-react\dist\views'

I've deleted node_modules and did npm install again, but that doesn't work.

**Dependencies versions**
Provide version numbers of following packages:

* semantic-ui-react ^0.84.0 inside semantic-ui-calendar-react package.json
* semantic-ui-css ^2.4.1 inside semantic-ui-calendar-react package.json
* semantic-ui-calendar-react ^0.14.0 in my package.json

**Comment by arfedulov** [comment]
Do you have semantic-ui-react installed?

**Comment by WassimMeddeb** [comment]
nah i already have the same  issue but your solution didn't work
