### ISSUE TITLE
The date picker with startmode year doesn't lets you change year

### ISSUE THREAD

**Issue by saranshinvy** [arfedulov/semantic-ui-calendar-react#93]
When you open date picker with startmode as year and then  you try to choose any year it would go back to current year and won't let you switch year.

You can test it out in your own example page in the 2nd example, pick any year except 2019 and it would automatically select 2019 only.

The same happens with choosing month.

It is happening with all examples, in the first example as well click on the year on top, and then try choosing any year except the current year and still 2019 would get chosen.

**Comment by arfedulov** [comment]
Yes, it's broken. Thanks for report.

**Comment by saranshinvy** [comment]
Well, loved the component would wait for you to fix it up, to use it.

**Comment by arfedulov** [comment]
Until it fixed you can use v0.13.0.

**Comment by saranshinvy** [comment]
Well thanks, i would also try looking if i can figure out the issue.

Thanks again.

**Comment by arfedulov** [comment]
I found what causes this problem. I'll fix it tomorrow.

**Comment by arfedulov** [comment]
fix merged
