### ISSUE TITLE
Can't change years and months

### ISSUE THREAD

**Issue by twens** [arfedulov/semantic-ui-calendar-react#94]
Can't change years and months

chrome
https://www.screencast.com/t/TMm8zPy2VLIy

ie
https://www.screencast.com/t/yZBVn7L2AO

**Comment by arfedulov** [comment]
a duplication #93

**Comment by twens** [comment]
take a look second video, please
now I have switched to 0.13.0 version - in chrome it is good, but in IE it has the same behavior
