### ISSUE TITLE
Can't change years and months in IE

### ISSUE THREAD

**Issue by twens** [arfedulov/semantic-ui-calendar-react#95]
version 0.13.0

Can't change years and months in IE

https://www.screencast.com/t/yZBVn7L2AO

**Comment by arfedulov** [comment]
Yes, this is different. I'll check this tomorrow.

**Comment by arfedulov** [comment]
I'm afraid that I can't help with this issue. It's just beyond my capabilities to keep this module working on IE. Any help is appreciated.
